### ISSUE TITLE
This doesn't show up in ASDF VM listing!

### ISSUE THREAD

**Issue by derpycoder** [salasrod/asdf-mkcert#4]
Hi @salasrod,

Your awesome ASDF plugin doesn't show up in [Official Plugin Collections](https://github.com/asdf-vm/asdf)!!

**Comment by salasrod** [comment]
Hi @abhijit-kar , I don't understand it's there in the readme: 
![image](https://user-images.githubusercontent.com/3689113/194682933-86f28610-cb81-4bec-9ad5-f785e6db89b1.png)

Is there another list where this is missing?

**Comment by derpycoder** [comment]
@salasrod,

I was wrong, I must have made a typo while searching for mkcert. 😅

I searched by `salasrod` and I can see all of your plugins listed. (caddy, mkcert, cockroach db).

Thank you for these plugins.
